import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import dts from 'vite-plugin-dts'
import { resolve } from 'path'

export default defineConfig({
  plugins: [
    vue(),
    dts({
      // rollupTypes intentionally NOT set — this project's installed TypeScript
      // (5.9.3) is newer than vite-plugin-dts's bundled API Extractor analysis
      // engine; with rollupTypes on, that mismatch made the "roll everything
      // into one bundled .d.ts" pass silently produce broken/incomplete output
      // (confirmed with a clean build). insertTypesEntry alone still gives every
      // lib entry a `<name>.d.ts` redirect to per-file declarations mirroring
      // src/ — correct, just not bundled into a single file.
      include: ['src/**/*.ts', 'src/**/*.vue'],
      // src/nuxt/**'s declarations are NOT generated here — vite-plugin-dts
      // produces empty output for src/nuxt/module.ts and src/nuxt/plugin.ts
      // specifically (their @nuxt/kit / ambient "#app" imports appear to be
      // more than the older analysis engine can resolve), regardless of entry
      // naming or rollupTypes. They're generated by a separate, narrowly-scoped
      // `tsc` pass instead — see the "build" script in package.json.
      exclude: ['src/nuxt/**'],
      outDir: 'dist',
      insertTypesEntry: true,
    }),
  ],
  build: {
    lib: {
      entry: {
        'vue-toast-kit': resolve(__dirname, 'src/index.ts'),
        'nuxt/module': resolve(__dirname, 'src/nuxt/module.ts'),
        'nuxt/plugin': resolve(__dirname, 'src/nuxt/plugin.ts'),
        testing: resolve(__dirname, 'src/testing.ts'),
      },
      formats: ['es', 'cjs'],
      fileName: (format, entryName) =>
        format === 'es' ? `${entryName}.js` : `${entryName}.cjs`,
    },
    rollupOptions: {
      // '#app' is a Nuxt-only virtual alias with no real module to resolve outside a
      // Nuxt app build — only src/nuxt/plugin.ts imports it, left unresolved here so
      // Nuxt's own bundler resolves it when it later processes dist/nuxt/plugin.js.
      external: ['vue', 'nuxt', '@nuxt/kit', 'pathe', '#app'],
      output: {
        globals: { vue: 'Vue' },
        assetFileNames: 'style.css',
      },
    },
    cssCodeSplit: false,
    sourcemap: true,
  },
  resolve: {
    alias: { '@': resolve(__dirname, 'src') },
  },
})
